// /src/components/tokens.js

const tokens = [
  {
    id: "0.0.5989978",
    name: "Kabila Token",
    symbol: "KBL",
    image: "/tokens/kbl.png",
    type: "FT",
  },
  {
    id: "0.0.8061363",
    name: "Kabila Staked",
    symbol: "xKBL",
    image: "/tokens/xkbl.png",
    type: "FT",
  },
  {
    id: "0.0.731861",
    name: "SaucerSwap",
    symbol: "SAUCE",
    image: "/tokens/sauce.png",
    type: "FT",
  },
  {
    id: "0.0.7907968",
    name: "DINO",
    symbol: "DINO",
    image: "/tokens/dino.png",
    type: "FT",
  },
  {
    id: "0.0.4571363",
    name: "Candy Token",
    symbol: "Candy",
    image: "/tokens/candy.png",
    type: "FT",
  },
  {
    id: "0.0.2283230",
    name: "Karate Combat",
    symbol: "KARATE",
    image: "/tokens/karate.png",type: "FT",
  },
  {
    id: "0.0.786931",
    name: "HbarSuite",
    symbol: "HSUITE",
    image: "/tokens/hsuite.png",type: "FT",
  },
  {
    id: "0.0.3716059",
    name: "DOVU",
    symbol: "DOVU",
    image: "/tokens/dovu.png",type: "FT",
  },
  {
    id: "0.0.4794920",
    name: "HashPack",
    symbol: "PACK",
    image: "/tokens/pack.png",type: "FT",
  },
  {
    id: "0.0.859814",
    name: "Calaxy",
    symbol: "CLXY",
    image: "/tokens/clxy.png",type: "FT",
  },
  {
    id: "0.0.968069",
    name: "HeadStarter",
    symbol: "HST",
    image: "/tokens/hst.png",type: "FT",
  },
  {
    id: "0.0.3210123",
    name: "STEAM",
    symbol: "STEAM",
    image: "/tokens/steam.png",type: "FT",
  },
  {
    id: "0.0.127877",
    name: "Tune.Fm",
    symbol: "JAM",
    image: "/tokens/jam.png",type: "FT",
  },

  {
    id: "0.0.4212",
    name: "hBARK",
    symbol: "HBARK",
    image: "/tokens/hbark.png",type: "FT",
  },
  {
    id: "0.0.4816828",
    name: "HBARbarian",
    symbol: "HBARBARIAN",
    image: "/tokens/hbarbarian.png",type: "FT",
  },
  {
    id: "0.0.1937609",
    name: "HeliSwap",
    symbol: "HELI",
    image: "/tokens/heli.png",type: "FT",
  },
  {
    id: "0.0.3706639",
    name: "Davincigraph",
    symbol: "DAVINCI",
    image: "/tokens/davinci.png",type: "FT",
  },
  {
    id: "0.0.1958126",
    name: "Diamond Standard Carat",
    symbol: "CARAT",
    image: "/tokens/carat.png",type: "FT",
  },
  {
    id: "0.0.4352885",
    name: "stickbug",
    symbol: "STICKBUG",
    image: "/tokens/stickbug.png",type: "FT",
  },
  {
    id: "0.0.4431990",
    name: "BankSocial",
    symbol: "BSL",
    image: "/tokens/bsl.png",type: "FT",
  },
  {
    id: "0.0.3176721",
    name: "SpaceApe",
    symbol: "SPACEAPE",
    image: "/tokens/spaceape.png",type: "FT",
  },
  {
    id: "0.0.1159074",
    name: "GRELF",
    symbol: "GRELF",
    image: "/tokens/grelf.png",type: "FT",
  },
  {
    id: "0.0.3155326",
    name: "BullBar",
    symbol: "BULL",
    image: "/tokens/bull.png",type: "FT",
  },
  {
    id: "0.0.6455559",
    name: "HbarTradingBot",
    symbol: "HTAI",
    image: "/tokens/htai.png",type: "FT",
  },
  {
    id: "0.0.834116",
    name: "HBARX",
    symbol: "HBARX",
    image: "/tokens/hbarx.png",type: "FT",
  },
  {
    id: "0.0.1460200",
    name: "xSAUCE",
    symbol: "XSAUCE",
    image: "/tokens/xsauce.png",type: "FT",
  },
  {
    id: "0.0.2964435",
    name: "Sauce Inu",
    symbol: "SAUCEINU",
    image: "/tokens/sauceinu.png",type: "FT",
  },

  //NFTs
  {
    id: "0.0.7111322",
    name: "AM OG",
    symbol: "AM OG",
    image: "/tokens/am_og.png",type: "NFT",
  },
  {
    id: "0.0.7900254",
    name: "GOJO CREW",
    symbol: "GOJO CREW",
    image: "/tokens/gojo_crew.png",type: "NFT",
  },
  {
    id: "0.0.7186774",
    name: "JungleTopBrand",
    symbol: "JTB",
    image: "/tokens/jtb.png",type: "NFT",
  },
  {
    id: "0.0.5959486",
    name: "Kabila Early INO Access",
    symbol: "KEIA",
    image: "/tokens/keia.png",type: "NFT",
  },
  {
    id: "0.0.5959530",
    name: "Kabila Early Years",
    symbol: "KEY",
    image: "/tokens/key.png",type: "NFT",
  },
  {
    id: "0.0.7561083",
    name: "LA RECONCHA",
    symbol: "LA RECONCHA",
    image: "/tokens/la_reconcha.png",type: "NFT",
  },
  {
    id: "0.0.7221638",
    name: "RALTS",
    symbol: "RALTS",
    image: "/tokens/ralts.png",type: "NFT",
  },
  {
    id: "0.0.7235629",
    name: "Santuario Hedera",
    symbol: "DRAGÓN",
    image: "/tokens/dragon.png",type: "NFT",
  },
  {
    id: "0.0.2179656",
    name: "SIWAS By Kabila",
    symbol: "SIWA",
    image: "/tokens/siwa.png",type: "NFT",
  },
  {
    id: "0.0.5297762",
    name: "Trofeos Miembro",
    symbol: "Miembro",
    image: "/tokens/miembro.png",type: "NFT",
  },
  {
    id: "0.0.5297663",
    name: "Trofeo Early Supporter",
    symbol: "EarlySupporter",
    image: "/tokens/earlysupporter.png",type: "NFT",
  },
  {
    id: "0.0.4581624",
    name: "HashPack x HMNKY",
    symbol: "HMNKY",
    image: "/tokens/hmnky.png",type: "NFT",
  },
  {
    id: "0.0.7443013",
    name: "Virgilios OG de CriptoATH",type: "NFT",
    symbol: "OG",
    image: "/tokens/og.png",
  },
  {
    id: "0.0.878200",
    name: "Dead Pixels Ghost Club",
    symbol: "DPGC",
    image: "/tokens/DPGC.png",type: "NFT",
  },
];

export default tokens;
